version: '3.3'
services:
  frontend:
    volumes:
      - ${PWD}:/app
    ports:
      - '4441:4200'
    container_name: oskarssuperapp_frontend
    image: oskarjoelssonffcg/oskarssuperapp:dev
    # build: .
  backend:
    ports:
      - '4442:4201'
    container_name: oskarssuperapp_backend
    image: oskarjoelssonffcg/oskarssuperapp_backend:dev
    # build: ./server/

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: supersecretuser
      MONGO_INITDB_ROOT_PASSWORD: supersecretpw
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: supersecretuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpw
