version: '3.3'
services:
  run:
    volumes:
      - ${PWD}../:/app
    ports:
      - '4200:4200'
    container_name: oskarssuperapp
    image: oskarjoelssonffcg/oskarssuperapp:dev

  # Use root/example as user/password credentials
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: supersecretuser
      MONGO_INITDB_ROOT_PASSWORD: supersecretpw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: supersecretuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpw
